version: '3.8'
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: 'Asia/Tokyo'
    ports:
      - '23306:3306'
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
