micronaut:
  application:
    name: todoApplicationWithMicronaut
datasources:
  default:
    url: jdbc:mysql://localhost:23306/todo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: app
    password: app
    dialect: MYSQL
    schema-generate: NONE
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
